### ISSUE TITLE
Proposal: Add a Multilangual Link preview.

### ISSUE THREAD

**Issue by hotdoy** [DeuxHuitHuit/link_preview#14]
So you can change the label depending on the user language.

**Comment by nitriques** [comment]
Would you like to change the value of the url also ? That would be trickier... But yeah, nice idea

**Comment by ShinShinman** [comment]
Hi.
Is there any access to Multilingual Text Box's other languages then default, maybe `{$field-name:lang}`? (Ad the moment `{$my-multilingual-txt-box-field-name}` gives me only values from default language.)

I need to add preview for second language (only two languages website). I don't mind another instance of Link Preview in a section but url has to contain entry title – different languages each time.

Thanks,
S.

**Comment by nitriques** [comment]
Hi @ShinShinman It's not possible at the moment, sorry.

**Comment by ShinShinman** [comment]
Got it. Thanks for answering.

**Comment by nitriques** [comment]
My pleasure. We hope to be able to create it sometime in 2017!

**Comment by nitriques** [comment]
The original issue has been fixed in e0fecf1bba610ad93c60b71e5e005017c2f532af and released in 1.4.0
