### ISSUE TITLE
No link in entry view

### ISSUE THREAD

**Issue by ShinShinman** [DeuxHuitHuit/link_preview#15]
Hi,
I'm coming back to this one #7.

There is no link in entry view for authors with Manager and Author user types. Reason is extension is trying to append link to `#context .actions` (which is an `<ul>` element) that is available only for Developers.

My workaround is to append `ul.actions` every time when it's not present. Like this 
`if ($('#context .actions').length == 0)	$('#context').append('<ul class="actions"></ul>');`

Hope I'm not messing up anything...
Regards,
Shin

**Comment by nitriques** [comment]
Which version are you using ? It's already been fixed.. https://github.com/DeuxHuitHuit/link_preview/commit/f4e760b644170e7007b9ff1880ec5c4d1902e34f

**Comment by ShinShinman** [comment]
Cool. Was using an old version.
Thanks,
S.

**Comment by nitriques** [comment]
Awesome. Thanks.
