### ISSUE TITLE
Preview button shown only when entry exists

### ISSUE THREAD

**Issue by jurajkapsz** [DeuxHuitHuit/link_preview#18]
Trying this extension for the first time. 

**Proposal**
The preview link button could be shown in page context only when the entry already exists, e.g. is edited and not being created. Otherwise it's just a broken link?

Not sure how to do it the nice way, I have tried to do it by checking for a `/new/` presence in window url path.

**Comment by nitriques** [comment]
Indeed this is confusing...

**Comment by nitriques** [comment]
> Not sure how to do it the nice way, 

In `displayPublishPanel()`, `$entry_id` will be null when creating an entry ;)

**Comment by nitriques** [comment]
[The fix is out](https://github.com/DeuxHuitHuit/link_preview/releases/tag/1.3.0)

**Comment by jurajkapsz** [comment]
> In displayPublishPanel(), $entry_id will be null when creating an entry ;)

Thanks for the lead!

> The fix is out

Your update works great!
